"use client";
import {createContext,useContext,useRef,useState,useEffect,ReactNode} from "react";
type Message={id:string;text:string;topic:string;files:string[];time:string};
type Locale="zh"|"en"|"es";
const labels={zh:{title:"从一次对话开始。",offline:"顾问暂未在线",online:"顾问在线",note:"客服尚未连接。内容仅保存在此浏览器，未发送给顾问。",topics:["规划旅程","已有行程","更改或取消"],input:"聊聊你的旅程…",save:"保存草稿",close:"关闭聊天",attach:"添加图片 / 文件",clear:"清除记录",empty:"无需注册。把你的想法留在这里，先从最重要的一件事聊起。",draft:"本地草稿 · 未发送",error:"请选择不超过 10MB 的图片、PDF 或 TXT 文件（最多 3 个）。",storage:"浏览器无法保存记录；关闭页面后内容可能丢失。"},en:{title:"A conversation comes first.",offline:"Advisors offline",online:"Advisors online",note:"Advisor service is not connected. Drafts stay in this browser and are not sent.",topics:["Plan a trip","Existing trip","Change or cancellation"],input:"Tell us about your journey…",save:"Save draft",close:"Close chat",attach:"Add image / file",clear:"Clear history",empty:"No account needed. Start with whatever matters most to your journey.",draft:"Local draft · Not sent",error:"Choose up to 3 images, PDFs or TXT files, each under 10MB.",storage:"Browser storage unavailable; your drafts may be lost when you leave."},es:{title:"Todo empieza hablando.",offline:"Asesores no disponibles",online:"Asesores disponibles",note:"El servicio aún no está conectado. Los borradores se guardan en este navegador y no se envían.",topics:["Planear un viaje","Viaje existente","Cambio o cancelación"],input:"Cuéntanos tu viaje…",save:"Guardar borrador",close:"Cerrar chat",attach:"Añadir imagen / archivo",clear:"Borrar historial",empty:"Sin cuenta. Empieza por lo que más importa para tu viaje.",draft:"Borrador local · No enviado",error:"Hasta 3 imágenes, PDF o TXT de menos de 10MB cada uno.",storage:"No se puede guardar en el navegador; puedes perder los borradores al salir."}};
type ChatContextValue={openChat:(topic?:string)=>void;setChatLocale:(locale:Locale)=>void};
const ChatContext=createContext<ChatContextValue>({openChat:()=>{},setChatLocale:()=>{}});
export const useChat=()=>useContext(ChatContext);
// Presence stays offline until a real transport can confirm advisor availability.
export type AdvisorPresence="online"|"offline";
export default function ChatProvider({children}:{children:ReactNode}){
 const [locale,setChatLocale]=useState<Locale>("zh"),[messages,setMessages]=useState<Message[]>([]),[text,setText]=useState(""),[topic,setTopic]=useState(""),[files,setFiles]=useState<File[]>([]),[error,setError]=useState("");
 const dialog=useRef<HTMLDialogElement>(null),fileInput=useRef<HTMLInputElement>(null),end=useRef<HTMLDivElement>(null),opener=useRef<HTMLElement|null>(null);const c=labels[locale];const presence:AdvisorPresence="offline";
 useEffect(()=>{let active=true;queueMicrotask(()=>{try{const raw=JSON.parse(localStorage.getItem("v1-chat-drafts")||"[]");if(active&&Array.isArray(raw))setMessages(raw.filter(m=>typeof m.id==="string"&&typeof m.text==="string"&&typeof m.topic==="string"&&typeof m.time==="string"&&Array.isArray(m.files)&&m.files.every((f:unknown)=>typeof f==="string")).slice(-50));}catch{/* Ignore unavailable or invalid local history. */}});return()=>{active=false};},[]);
 useEffect(()=>{end.current?.scrollIntoView({block:"nearest"});},[messages]);
 const persist=(next:Message[])=>{setMessages(next);try{localStorage.setItem("v1-chat-drafts",JSON.stringify(next));}catch{setError(c.storage);}};
 const openChat=(subject="")=>{opener.current=document.activeElement as HTMLElement;if(subject)setTopic(subject);dialog.current?.showModal();};
 return <ChatContext.Provider value={{openChat,setChatLocale}}>{children}<button className="chat-launcher" onClick={()=>openChat()} aria-haspopup="dialog"><span className="status-dot"/> TALK TO V1 ↗</button><div className="mobile-bar"><button onClick={()=>openChat(c.topics[0])}>{c.topics[0]} ↗</button><button onClick={()=>openChat()}>TALK TO V1 ↗</button></div>
 <dialog ref={dialog} className="chat-dialog live-chat" aria-labelledby="chat-title" onClose={()=>opener.current?.focus()}><header className="chat-header"><div>V1 TRAVEL / GUEST<span className="presence" data-status={presence}>{c[presence]}</span></div><button autoFocus aria-label={c.close} onClick={()=>dialog.current?.close()}>×</button></header><div className="chat-scroll"><p className="eyebrow">A HUMAN TO HELP.</p><h2 id="chat-title">{c.title}</h2><p>{c.empty}</p><div className="chat-options">{c.topics.map(t=><button aria-pressed={topic===t} key={t} onClick={()=>setTopic(t)}>{t} ↗</button>)}</div><p className="chat-notice">{c.note}</p>{topic&&<p className="topic">↗ {topic}</p>}<div role="log" aria-live="polite" aria-relevant="additions">{messages.map(m=><article className="chat-message" key={m.id}>{m.topic&&<small>{m.topic}</small>}<p>{m.text}</p>{m.files.map((f,i)=><p key={i}>↳ {f}</p>)}<small>{c.draft} · {new Date(m.time).toLocaleTimeString(locale,{hour:"2-digit",minute:"2-digit"})}</small></article>)}<div ref={end}/></div>{messages.length>0&&<button className="clear-chat" onClick={()=>persist([])}>{c.clear}</button>}</div>
 <form className="chat-composer" onSubmit={e=>{e.preventDefault();if(!text.trim()&&!files.length)return;persist([...messages,{id:crypto.randomUUID(),text:text.trim(),topic,files:files.map(f=>f.name),time:new Date().toISOString()}].slice(-50));setText("");setFiles([]);}}><div className="attachment-list">{files.map((f,i)=><button type="button" key={i} onClick={()=>setFiles(files.filter((_,j)=>j!==i))} aria-label={`Remove ${f.name}`}>{f.name} ×</button>)}</div><textarea aria-label={c.input} placeholder={c.input} value={text} maxLength={4000} onChange={e=>setText(e.target.value)} rows={3}/><input hidden ref={fileInput} type="file" multiple accept="image/jpeg,image/png,image/webp,image/gif,application/pdf,text/plain" onChange={e=>{const chosen=Array.from(e.target.files||[]);if(files.length+chosen.length>3||chosen.some(f=>f.size>10*1024*1024||!["image/jpeg","image/png","image/webp","image/gif","application/pdf","text/plain"].includes(f.type))){setError(c.error);}else{setFiles([...files,...chosen]);setError("");}e.target.value="";}}/><div className="composer-actions"><button type="button" onClick={()=>fileInput.current?.click()}>{c.attach} +</button><button disabled={!text.trim()&&!files.length}>{c.save} ↑</button></div>{error&&<p role="alert">{error}</p>}</form></dialog></ChatContext.Provider>;
}
